 CREATE TABLE `amocrm_leads` (
  `id_inc` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(15) NOT NULL DEFAULT '0',
  `closed_at` int(11) NOT NULL DEFAULT '0',
  `closest_task_at` int(11) NOT NULL DEFAULT '0',
  `company$id` int(15) NOT NULL DEFAULT '0',
  `company$_links$self$href` varchar(50) NOT NULL DEFAULT '',
  `company$_links$self$method` varchar(10) NOT NULL DEFAULT '',
  `company$name` varchar(500) NOT NULL DEFAULT '',
  `contacts$id` int(15) NOT NULL DEFAULT '0',
  `contacts$_links$self$href` varchar(50) NOT NULL DEFAULT '',
  `contacts$_links$self$method` varchar(10) NOT NULL DEFAULT '',
  `created_at` int(11) NOT NULL DEFAULT '0',
  `created_by` int(15) NOT NULL DEFAULT '0',
  `custom_fields` varchar(500) NOT NULL DEFAULT '',
  `group_id` int(15) NOT NULL DEFAULT '0',
  `id` int(15) NOT NULL DEFAULT '0',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `_links$self$href` varchar(50) NOT NULL DEFAULT '',
  `_links$self$method` varchar(10) NOT NULL DEFAULT '',
  `loss_reason_id` int(15) NOT NULL DEFAULT '0',
  `main_contact$id` int(15) NOT NULL DEFAULT '0',
  `main_contact$_links$self$href` varchar(50) NOT NULL DEFAULT '',
  `main_contact$_links$self$method` varchar(10) NOT NULL DEFAULT '',
  `name` varchar(300) NOT NULL DEFAULT '',
  `pipeline_id` int(15) NOT NULL DEFAULT '0',
  `pipeline$id` int(15) NOT NULL DEFAULT '0',
  `pipeline$_links$self$href` varchar(50) NOT NULL DEFAULT '',
  `pipeline$_links$self$method` varchar(10) NOT NULL DEFAULT '',
  `responsible_user_id` int(15) NOT NULL DEFAULT '0',
  `sale` int(15) NOT NULL DEFAULT '0',
  `status_id` int(15) NOT NULL DEFAULT '0',
  `tags` varchar(500) NOT NULL DEFAULT '',
  `updated_at` int(11) NOT NULL DEFAULT '0',
  `updated_by` int(15) NOT NULL DEFAULT '0',
  `params$service` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_inc` (`id_inc`),
  KEY `in_amocrm_leads$created_by` (`created_by`),
  KEY `in_amocrm_leads$created_at` (`created_at`),
  KEY `in_amocrm_leads$pipeline_id` (`pipeline_id`),
  KEY `in_amocrm_leads$responsible_user_id` (`responsible_user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=12211 DEFAULT CHARSET=utf8;


CREATE TABLE `amocrm_notes` (
  `id_inc` int(11) NOT NULL AUTO_INCREMENT,
  `id` int(15) NOT NULL DEFAULT '0',
  `created_by` int(15) NOT NULL DEFAULT '0',
  `account_id` int(15) NOT NULL DEFAULT '0',
  `group_id` int(15) NOT NULL DEFAULT '0',
  `is_editable` tinyint(1) NOT NULL DEFAULT '0',
  `element_id` int(15) NOT NULL DEFAULT '0',
  `element_type` int(3) NOT NULL DEFAULT '0',
  `text` varchar(1000) NOT NULL DEFAULT '',
  `note_type` int(5) NOT NULL DEFAULT '0',
  `created_at` int(11) NOT NULL DEFAULT '0',
  `updated_at` int(11) NOT NULL DEFAULT '0',
  `responsible_user_id` int(15) NOT NULL DEFAULT '0',
  `params` varchar(500) NOT NULL DEFAULT '',
  `attachment` varchar(25) NOT NULL DEFAULT '',
  `_links$self$href` varchar(50) NOT NULL DEFAULT '',
  `_links$self$method` varchar(10) NOT NULL DEFAULT '',
  `params$access_granted` int(3) NOT NULL DEFAULT '0',
  `params$attach_cnt` int(5) NOT NULL DEFAULT '0',
  `params$content_summary` varchar(1000) NOT NULL DEFAULT '',
  `params$contentSummary` varchar(1000) NOT NULL DEFAULT '',
  `params$delivery$status` varchar(250) NOT NULL DEFAULT '',
  `params$delivery$time` int(15) NOT NULL DEFAULT '0',
  `params$from$email` varchar(250) NOT NULL DEFAULT '',
  `params$from$name` varchar(250) NOT NULL DEFAULT '',
  `params$HTML` varchar(1000) NOT NULL DEFAULT '',
  `params$income` tinyint(1) NOT NULL DEFAULT '0',
  `params$LOSS_REASON_ID` int(15) NOT NULL DEFAULT '0',
  `params$message_id` int(15) NOT NULL DEFAULT '0',
  `params$PIPELINE_ID_NEW` int(15) NOT NULL DEFAULT '0',
  `params$PIPELINE_ID_OLD` int(15) NOT NULL DEFAULT '0',
  `params$private` tinyint(1) NOT NULL DEFAULT '0',
  `params$STATUS_NEW` int(15) NOT NULL DEFAULT '0',
  `params$STATUS_OLD` int(15) NOT NULL DEFAULT '0',
  `params$subject` varchar(1000) NOT NULL DEFAULT '',
  `params$TEXT` varchar(1000) NOT NULL DEFAULT '',
  `params$thread_id` int(15) NOT NULL DEFAULT '0',
  `params$to$email` varchar(250) NOT NULL DEFAULT '',
  `params$to$name` varchar(250) NOT NULL DEFAULT '',
  `params$version` int(3) NOT NULL DEFAULT '0',
  `params$DURATION` int(15) NOT NULL DEFAULT '0',
  `params$PHONE` varchar(25) NOT NULL DEFAULT '0',
  `params$LINK` varchar(150) NOT NULL DEFAULT '0',
  `params$SRC` varchar(15) NOT NULL DEFAULT '0',
  `params$UNIQ` varchar(20) NOT NULL DEFAULT '0',
  `params$call_status` int(3) DEFAULT NULL,
  `updated_by` int(11) NOT NULL DEFAULT '0',
  `params$service` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_inc` (`id_inc`),
  KEY `in_amocrm_notes$element_id` (`element_id`),
  KEY `in_amocrm_notes$created_by` (`created_by`),
  KEY `in_amocrm_notes$responsible_user_id` (`responsible_user_id`),
  KEY `in_amocrm_notes$updated_at` (`updated_at`)
) ENGINE=InnoDB AUTO_INCREMENT=65876 DEFAULT CHARSET=utf8;


CREATE TABLE `amocrm_tasks` (
  `id_inc` int(11) NOT NULL AUTO_INCREMENT,
  `id` int(15) NOT NULL DEFAULT '0',
  `element_id` int(15) NOT NULL DEFAULT '0',
  `element_type` int(15) NOT NULL DEFAULT '1',
  `complete_till_at` int(11) DEFAULT NULL,
  `task_type` int(11) DEFAULT NULL,
  `text` varchar(500) NOT NULL DEFAULT '',
  `created_at` int(11) NOT NULL DEFAULT '0',
  `updated_at` int(11) NOT NULL DEFAULT '0',
  `responsible_user_id` int(15) DEFAULT NULL,
  `is_completed` tinyint(1) NOT NULL DEFAULT '0',
  `created_by` int(15) NOT NULL DEFAULT '0',
  `account_id` int(15) NOT NULL DEFAULT '0',
  `group_id` int(15) DEFAULT NULL,
  `duration` int(11) NOT NULL DEFAULT '0',
  `_links$self$href` varchar(50) NOT NULL DEFAULT '',
  `_links$self$method` varchar(10) NOT NULL DEFAULT '',
  `result$id` int(15) NOT NULL DEFAULT '0',
  `result$_links$self$href` varchar(50) NOT NULL DEFAULT '',
  `result$_links$self$method` varchar(10) NOT NULL DEFAULT '',
  `result$text` varchar(1000) NOT NULL DEFAULT '',
  `updated_by` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_inc` (`id_inc`),
  KEY `in_amocrm_tasks$element_id` (`element_id`),
  KEY `in_amocrm_tasks$responsible_user_id` (`responsible_user_id`),
  KEY `in_amocrm_tasks$updated_at` (`updated_at`),
  KEY `in_amocrm_tasks$created_at` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=81833 DEFAULT CHARSET=utf8;
